# Generated by Django 4.2.1 on 2023-06-04 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participant", "0005_team_project_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="project_image",
            field=models.ImageField(default="images/default.png", upload_to="images/"),
        ),
    ]
