# Generated by Django 4.2.1 on 2023-06-05 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participant", "0006_alter_team_project_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="project_source_code",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="team",
            name="project_video_url",
            field=models.CharField(default="", max_length=100),
        ),
    ]
